# Generated by Django 3.2.8 on 2021-10-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False},
        ),
    ]
